#!/usr/bin/env node
/**
 * Overhead power lines around the circuit (the 77 kV 新鈴鹿河芸線 pylons that stand behind Turns
 * 1–2, the main straight and the west side are in every TV wide shot). Queries Overpass for
 * power=tower nodes and power=line ways in a 3.4 × 2.6 km box around the circuit, projects them
 * into the project's local EN frame (same projection as CENTERLINE_EN) and writes
 * app/data/suzuka-power.ts. ODbL: the output is OpenStreetMap-derived data.
 *
 *   node scripts/facilities/build-power.mjs            # query + write
 *   node scripts/facilities/build-power.mjs --offline  # reuse the cached response
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const OUT = path.join(ROOT, 'app/data/suzuka-power.ts')
const CACHE = path.join(process.env.TMPDIR ?? '/tmp', 'suzuka-power-overpass.json')
const UA = 'suzuka3d-facilities/1.0 (bhyg756@gmail.com)'
// jp-1962 equirectangular frame (see build-facilities.mjs)
const D = Math.PI / 180, R = 6378137, LAT0 = 34.844581633720921, LON0 = 136.53282038953489
const KX = Math.cos(LAT0 * D) * R * D, KY = R * D
const toEN = (lon, lat) => [Number(((lon - LON0) * KX).toFixed(1)), Number(((lat - LAT0) * KY).toFixed(1))]

const QUERY = `[out:json][timeout:120];
(
  node[power=tower](34.828,136.512,34.860,136.556);
  way[power=line](34.828,136.512,34.860,136.556);
);
out body geom;`

async function load () {
  if (process.argv.includes('--offline') && fs.existsSync(CACHE)) return JSON.parse(fs.readFileSync(CACHE, 'utf8'))
  for (const url of ['https://overpass-api.de/api/interpreter', 'https://overpass.kumi.systems/api/interpreter']) {
    try {
      const res = await fetch(url, { method: 'POST', headers: { 'User-Agent': UA }, body: new URLSearchParams({ data: QUERY }) })
      if (!res.ok) throw new Error(`${res.status}`)
      const json = await res.json()
      fs.writeFileSync(CACHE, JSON.stringify(json))
      return json
    } catch (err) { console.warn(`${url}: ${err.message}`) }
  }
  throw new Error('Overpass unavailable')
}

const json = await load()
const date = new Date().toISOString()
const towers = json.elements.filter((e) => e.type === 'node' && e.tags?.power === 'tower').map((e) => ({ id: e.id, en: toEN(e.lon, e.lat) }))
const lines = json.elements.filter((e) => e.type === 'way' && e.geometry).map((e) => ({
  id: e.id,
  name: e.tags?.name ?? '',
  voltage: e.tags?.voltage ? Number(e.tags.voltage) : null,
  cables: e.tags?.cables ? Number(e.tags.cables) : null,
  en: e.geometry.map((g) => toEN(g.lon, g.lat)),
}))
const text = `/**
 * Overhead power lines around Suzuka Circuit — GENERATED by scripts/facilities/build-power.mjs,
 * do not edit by hand.
 *
 * Data © OpenStreetMap contributors, licensed under the Open Database License (ODbL) 1.0,
 * https://opendatacommons.org/licenses/odbl/1-0/ — this file is an OpenStreetMap-derived
 * database. Overpass extract ${date}. Coordinates are local EN metres in the jp-1962 frame
 * (Track.enToWorld converts them to world space).
 */

export interface PowerTower { id: number; en: [number, number] }
export interface PowerLine { id: number; name: string; voltage: number | null; cables: number | null; en: [number, number][] }

export const OSM_POWER_TOWERS: PowerTower[] = ${JSON.stringify(towers)}

export const OSM_POWER_LINES: PowerLine[] = ${JSON.stringify(lines)}
`
fs.writeFileSync(OUT, text)
console.log(`${towers.length} towers, ${lines.length} lines → ${OUT} (${(text.length / 1024).toFixed(1)} KB)`)
